package:
  name: srahunter
  version: 0.0.1

source:
  git_url: https://github.com/GitEnricoNeko/SRAHunter
  git_branch: main
build:
  entry_points:
    - srahunter=scripts.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vvv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - datavzrd
    - entrez-direct
    - python >=3.6
    - pandas >=2.0.2
    - psutil >=5.7
    - pyfiglet
    - requests ==2.31.0
    - tqdm ==4.66.1
    - sra-tools

test:
  commands:
    - pip check
    - srahunter --help
  requires:
    - pip

about:
  home: https://github.com/GitEnricoNeko/SRAHunter
  license: MIT
  license_file: LICENSE
  summary: "SRAHunter is a tool for processing SRA accession numbers."


