package:
  name: srahunter
  version: 1.0.0

source:
  url:    https://github.com/GitEnricoNeko/SRAHunter/archive/refs/tags/1.0.0.tar.gz
  sha256: 6c9993685aa715e81c04972791f9fbaf5f21a30700d860bdc17d9b86237f8de0
build:
  entry_points:
    - srahunter=scripts.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vvv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - datavzrd
    - entrez-direct
    - python >=3.6
    - pandas >=2.0.2
    - psutil >=5.7
    - pyfiglet
    - requests >=2.31.0
    - tqdm >=4.66.1
    - sra-tools

test:
  commands:
    - pip check
    - srahunter --help
  requires:
    - pip

about:
  home: https://github.com/GitEnricoNeko/SRAHunter
  license: MIT
  license_file: LICENSE
  summary: "SRAHunter is a tool for processing SRA accession numbers."

